# These are supported funding model platforms
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# doesn't seem to work:
# github: lukesampson
patreon: #
open_collective: #
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
# causes this error:  
# Sponsor ScoopInstaller/Scoop
# 
# Some errors were encountered when parsing the FUNDING.yml file:
# 
#     Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.
# 
# Learn more about formatting FUNDING.yml.
# External links
# https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=DM2SUH9EUXSKJ 
# 
# custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=DM2SUH9EUXSKJ
